### ISSUE TITLE
Pass github context variables as env variables automatically

### ISSUE THREAD

**Issue by spencerschrock** [ossf/scorecard-dependencyanalysis#1]
The example workflow has this:
```
jobs:
  dependency-analysis:
    name: Scorecards dependency analysis
    runs-on: ubuntu-latest
    env:
      GITHUB_PR_NUMBER: ${{ github.event.number }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_REPOSITORY: ${{ github.repository }}
      GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
      GITHUB_SHA: ${{ github.sha }}
      GITHUB_ACTOR: ${{ github.actor }}
```

This should all be accessible from the github context by this action, right? Instead of having the caller do this, would it be worthwhile to change action.yml to do this?
https://github.com/ossf/scorecard-dependencyanalysis/blob/c647ca87e668983c56bba5dae038d63394f4ed0e/action.yaml#L21-L23
https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runsenv
